server:
  port: ${PORT:9008}
  tomcat:
    max-threads: 1
  
spring:
  application:
    name: item-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current-session-context-class: thread
        format-sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: http://${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: item-group
      enable-auto-commit: "true"


