
spring:
  application:
    name: item-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      discovery:
        enabled: true
        service-id: config-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetchRegistry: true
